name: Build and Deploy Code

on: [push, pull_request]

# In order for environment variables to be accessible across all the jobs add environment variable on the top  before jobs 

jobs:
  job1: 
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: admin123
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    runs-on: ubuntu-latest

    steps: 
      - name: pulling git repo
        uses: actions/checkout@v5
      - name: Install Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'  
      - name: Update pip
        run: python3 -m pip install --upgrade pip
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: run the test cases
        run: |
          pip3 install pytest
          pytest --disable-warnings -v -s


         
